spring:
  datasource:
    url: jdbc:mysql://localhost:3306/likeflower?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: cheese
  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
graphql:
 servlet:
  mapping: /graphql
  enabled: true

graphiql:
 endpoint:
  graphql: /graphql
 mapping: /graphiql
 
grokonez:
 app:
  jwtSecret: xuIdQGSUNtACY2T0mQO1j0xKGaEL506f5H2eZx6F7vZI5VmFh/QJMLxgQNhn8sJyrXLGmoPp9HUauexWaez1jw==